apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: dev
  labels:
    app: nginx-app
    environment: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
  selector:
    app: nginx-app
